from pydantic import BaseModel, Field, EmailStr
from typing import Dict, List, Optional

# Simple alias for identifier strings
ID = str

class User(BaseModel):
    """
    User represents a plan participant. No authentication - users are per-plan labels only.
    User ID is NOT part of this structure - it's the dictionary key in Plan.users (Task.users).
    """
    displayName: str = Field(..., min_length=1, description="Display name shown in UI")
    firstName: Optional[str] = Field(None, description="Optional first name for full name display")
    lastName: Optional[str] = Field(None, description="Optional last name for full name display")
    email: Optional[EmailStr] = Field(None, description="Optional email for contact/sharing (not globally unique)")
    phoneNumber: Optional[str] = Field(None, description="Optional phone number for contact/sharing")

class TaskBase(BaseModel):
    id: ID
    title: str
    description: Optional[str] = None
    result: Optional[str] = None
    status: str
    authorId: ID
    assigneeId: Optional[ID] = None
    subtaskIds: List[ID] = Field(default_factory=list)
    parentId: Optional[ID] = None
    createdAt: str
    updatedAt: Optional[str] = None

class Task(TaskBase):
    users: Optional[Dict[str, User]] = Field(None, description="Dictionary of users keyed by user ID (e.g., 'user-1', 'user-2')")
    accessKey: Optional[str] = None

class TaskCreate(BaseModel):
    id: ID = Field(..., description="Task ID (UUID v4) generated by client")
    title: str
    description: Optional[str] = None
    authorId: ID
    assigneeId: Optional[ID] = None
    parentId: Optional[ID] = None
    status: Optional[str] = Field("new", description="Task status (new, in-progress, done, etc.)")

class TaskUpdate(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    result: Optional[str] = None
    status: Optional[str] = None
    assigneeId: Optional[ID] = None
    subtaskIds: Optional[List[ID]] = None
    users: Optional[Dict[str, User]] = None
    accessKey: Optional[str] = None
